apiVersion: v1
kind: ConfigMap
metadata:
  name: mintaxetaxconfigmap
data:
  appsettings.json: |
    {
      "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "MintaxConnection": "server=mintax-test-etax-mariadb;port=3306;database=misa_etaxmintax_test;user=root;password=misa@2020;CharSet=utf8;",
        "Catalog": "server=mintax-amis-database;port=3306;database=misa_amismintax_test;user=root;password=misa@2020;CharSet=utf8;",
        "ServertocreateMultitenant": "server=mintax-test-etax-mariadb;port=3306;user=root;password=misa@2020;CharSet=utf8;"
      },
      "MaxWeighPerDatabase": 100,
      "RedisCacheConfig": {
        "InstanceName": "ETaxMultitenantDB",
        "RedisHost": "mintax-redis-etax-master"
      },
      "AmisConnector": {
        "BaseURL": "http://mintax-amisconnector/amisconnector/api/v1"
      } 
    }
