apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ include "mintax.fullname" . }}-web
 labels:
{{ include "mintax.labels" . | indent 4 }}-web
data:
 appsettings.json: |
  {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "AllowedHosts": "*"
  }
