apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ include "mintax.fullname" . }}-etax
 labels:
{{ include "mintax.labels" . | indent 4 }}-etax
data:
 appsettings.json: |
  {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "ConnectionStrings": {
      "MintaxConnection": "server={{ tpl .Values.dbhost . }};port={{ .Values.dbport }};database={{ .Values.dbname }};user={{ .Values.dbuser }};password={{ .Values.dbpass }};CharSet=utf8"
    },
    "AllowedHosts": "*"
  }

