apiVersion: v1
kind: ConfigMap
metadata:
  name: mintaxworkerconfigmap
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "ConnectionStrings": {
        "MintaxConnection": "server=mintax-test-etax-mariadb;port=3306;database=misa_etaxmintax_test;user=root;password=misa@2020;CharSet=utf8"
      },
      "AllowedHosts": "*"
    }
