apiVersion: v1
kind: ConfigMap
metadata:
 name: mintaxtest-web
data:
 appsettings.json: |
  {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "AllowedHosts": "*"
  }
