apiVersion: v1
kind: ConfigMap
metadata:
  name: mintaxamisconfigmap
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "AmisSetting": {
        "x-clientid": "327d19ed-6e0a-486e-8733-87bd82d5c794",
        "x-clientsecret": "N1UmccCVDGh2mXQMHCtcIZhHGIqnULoeGvk5RfMwX/Q=",
        "amisUrl": "http://test-k8s-master-01.rdp.local:30573"
      },
      "ConnectionStrings": {
         "AmisConnection": "server=mintax-amis-database;port=3306;database=misa_amismintax_test;user=root;password=misa@2020;CharSet=utf8"
      },
      "AppSettings": {
        "Token" : "MyTokenScreatKey"
      }
    }
