//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Mintax.ETax.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Mintax.ETax.ApplicationCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tờ khai kèm theo.
        /// </summary>
        public static string DeclarationNotFound {
            get {
                return ResourceManager.GetString("DeclarationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi trùng dữ liệu..
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thêm mới tờ khai.
        /// </summary>
        public static string ErrorAddDeclaration {
            get {
                return ResourceManager.GetString("ErrorAddDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thêm mới dữ liệu..
        /// </summary>
        public static string ErrorAddEntity {
            get {
                return ResourceManager.GetString("ErrorAddEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi bind NNT.
        /// </summary>
        public static string ErrorBindNNT {
            get {
                return ResourceManager.GetString("ErrorBindNNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi bind TKhaiThue.
        /// </summary>
        public static string ErrorBindTaxRecord {
            get {
                return ResourceManager.GetString("ErrorBindTaxRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi build thông tin đại lý thuế không hợp lệ..
        /// </summary>
        public static string ErrorBuildDLyThue {
            get {
                return ResourceManager.GetString("ErrorBuildDLyThue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build dữ liệu bị lỗi phần thông tin chung..
        /// </summary>
        public static string ErrorBuilding {
            get {
                return ResourceManager.GetString("ErrorBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi build tờ khai..
        /// </summary>
        public static string ErrorBuildingDeclaration {
            get {
                return ResourceManager.GetString("ErrorBuildingDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn vị tổ chức không đúng..
        /// </summary>
        public static string ErrorBuildNNT {
            get {
                return ResourceManager.GetString("ErrorBuildNNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tính toán tờ khai thuế..
        /// </summary>
        public static string ErrorCaculatorDeclaration {
            get {
                return ResourceManager.GetString("ErrorCaculatorDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xóa được tờ khai đi kèm..
        /// </summary>
        public static string ErrorDeleteDeclaration {
            get {
                return ResourceManager.GetString("ErrorDeleteDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xóa dữ liệu..
        /// </summary>
        public static string ErrorDeleteEntity {
            get {
                return ResourceManager.GetString("ErrorDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giảm không được phép trống ngày kết thúc phụ thuộc.
        /// </summary>
        public static string ErrorFinishDependentDate {
            get {
                return ResourceManager.GetString("ErrorFinishDependentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không cập nhật được tờ khai thuế đi kèm..
        /// </summary>
        public static string ErrorUpdateDeclaration {
            get {
                return ResourceManager.GetString("ErrorUpdateDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cập nhật dữ liệu..
        /// </summary>
        public static string ErrorUpdateEntity {
            get {
                return ResourceManager.GetString("ErrorUpdateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Exception..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi đã tồn tại dữ liệu..
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi File Export không đúng định dạng.
        /// </summary>
        public static string ExportFileFormat {
            get {
                return ResourceManager.GetString("ExportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi File không đúng định dạng..
        /// </summary>
        public static string FileFormat {
            get {
                return ResourceManager.GetString("FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi File import không đúng định dạng..
        /// </summary>
        public static string ImportFileFormat {
            get {
                return ResourceManager.GetString("ImportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tổ chức không đúng..
        /// </summary>
        public static string InvalidOrganization {
            get {
                return ResourceManager.GetString("InvalidOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không khả dụng..
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotBindingAgain {
            get {
                return ResourceManager.GetString("NotBindingAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ số lượng bảng tạm tính. .
        /// </summary>
        public static string NotEnough {
            get {
                return ResourceManager.GetString("NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không tìm thấy dữ liệu..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không hợp lệ..
        /// </summary>
        public static string TimeInvalid {
            get {
                return ResourceManager.GetString("TimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi validate dữ liệu chung..
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi validate dữ liệu do không đúng nghiệp vụ..
        /// </summary>
        public static string ValidateBussiness {
            get {
                return ResourceManager.GetString("ValidateBussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi validate dữ liệu không hợp lệ..
        /// </summary>
        public static string ValidateEntity {
            get {
                return ResourceManager.GetString("ValidateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu thông tin đơn vị..
        /// </summary>
        public static string ValidateOrganization {
            get {
                return ResourceManager.GetString("ValidateOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo trùng thông tin..
        /// </summary>
        public static string WarningChangeInfo {
            get {
                return ResourceManager.GetString("WarningChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo thay đổi thông tin..
        /// </summary>
        public static string WarningUpdateData {
            get {
                return ResourceManager.GetString("WarningUpdateData", resourceCulture);
            }
        }
    }
}
