apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "etax.fullname" . }}-configmap
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "ConnectionStrings": {
        "MintaxConnection": "server=mintax-etax-database;port=3306;database=misa_etaxmintax_demo;user=root;password=misa@2020;CharSet=utf8"
      },
      "AmisConnector": {
        "BaseURL": "http://mintax-amisconnector/amisconnector/api/v1"
      },
      "AllowedHosts": "*"  
    }
